#pragma once

#if defined (ORBITAL_OPENGL)
#define OE_FALSE GL_FALSE
#define OE_TRUE GL_TRUE

#define OE_FLOAT GL_FLOAT

#define OE_STATIC_DRAW GL_STATIC_DRAW
#define OE_DYNAMIC_DRAW GL_DYNAMIC_DRAW

#define OE_TRIANGLES GL_TRIANGLES

#define OE_REPEAT GL_REPEAT;
#define OE_MIRRORED_REPEAT GL_MIRRORED_REPEAT;
#define OE_CLAMP_TO_EDGE GL_CLAMP_TO_EDGE;
#define OE_CLAMP_TO_BORDER GL_CLAMP_TO_BORDER;
#endif